### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by normanlolx** [wodby/wordpress-composer#5]
As I already said I find this template by far the best Composer template for WordPress. It doesn't produce any overhead and keeps the WordPress file structure as original as possible. So, yeah I really like it and will definitely take this as my base from now on. And that's also the point where I'm wondering if you are open for any improvements.

Nothing dramatic. Just requiring `wp-cli/wp-cli` for example, or pre-configuring `"bin-dir": "bin/"` and maybe even add some initial `ScriptHandler.php` (although I'm not sure what it could do for now except copying the `wp-config-sample.php`). More or less all in direction of the https://github.com/drupal-composer/drupal-project template. (I'm also currently working on a `drush-launcher` equivalent for `wp-cli` and hope to get it released beginning next week).

I'm totally fine if you reject. It's just I'd prefer to contribute to this repo instead of forking it and start just another template (there are too much different WordPress templates out there already IMHO). And I also find that your template deserves more attention, and maybe these improvements can help :)

**Comment by csandanov** [comment]
We're open for improvements and suggestions in general. 

Are there any issues with different 4.x version of WP and version of WP CLI? Drupal includes drush and console it because:
* there's a lot of compatibility issues between different minor versions of drush, some drush versions don't support certain versions of Drupal
* both drush and console use the same dependencies as Drupal like symfony/console, so it's important to have them coupled to avoid versions conflicts

Also, the typical use for this project is to be used with docker, see https://github.com/wodby/docker4wordpress, the image [wordpress-php ](https://github.com/wodby/wordpress-php) already comes with preinstalled global wp cli and I haven't heard so far of any compability issues. But if they exists and we want to resolve them, then yes, we'll need the launcher.

**Comment by normanlolx** [comment]
`wp-cli-launcher` would be for convenience first of all. But I'd also like it to trigger at least a warning or something else when a user runs `wp core update` or `wp plugin update` to notify that the current project's dependencies are managed by composer and that you'd better run `composer udpate` instead.

**Comment by normanlolx** [comment]
Yesterday I finally tagged v1.0.0 of my Composer template for WordPress projects.

https://github.com/leymannx/wordpress-project

It's a fork of https://github.com/drupal-composer/drupal-project.

The https://github.com/leymannx/wp-cli-launcher is still WIP but it's working so far with all popular Composer templates for WordPress (including https://github.com/wodby/wordpress-composer).
